# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 793ba3e714bf7f3c2a5d421321bd2938f5c0b03a14ba4797b09bba659e39198da7e91df7d06074b1fbc69a05b1124868bf89ede7fdee5faa8168dcfbb15ef540

test:
  secret_key_base: 5bb51c80d851df9f95ce18bf3c5d82ef4503368c8ccd4502ecf34db1b5ffc7fa4aa25cc5316a787755f8ad854cb488c746c7552f39cfeac6dc535c14b60b1009

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
